
---

- hosts: all
  become: yes
  tasks:

  - name: install apache2, php packages and update index Ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
#      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

#Commands for CentOS
  - name: install apache2, php packages and update index for CentOS
    dnf:
      name: 
         - httpd
         - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["CentOS","RedHat"]
