---

- hosts: all
  become: yes
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: install apche2 package
    apt:
      name: apache2
      state: latest

  - name: add php suport for apache
    apt:
      name: libapache2-mod-php
      state: latest
