
---

- hosts: all
  become: yes
  tasks:

#  - name: Update repository index
#    apt:
#      update_cache: true
#    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]

#Commands for CentOS
  - name: Update repository index
    dnf:
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php packages for CentOS
    dnf:
      name: 
         - httpd
         - php
      state: latest
    when: ansible_distribution in ["CentOS","RedHat"]
