
---

- hosts: all
  become: yes
  tasks:

  - name: install apache, php packages and update index
    package:
      name: 
         #Using variables defined in the inventory file
         - "{{ apache_package }}"
         - "{{ php_package }}"
      state: latest
#      update_cache: yes
