---

- hosts: all
  become: yes
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
      state: absent

  - name: remove apche2 package
    apt:
      name: apache2
      state: absent

  - name: remove php suport for apache
    apt:
      name: libapache2-mod-php
      state: absent
