
---
#Install targetting specific hosts
- hosts: all
  become: yes
  pre_tasks:

  - name: install update (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
#      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform from a zip file
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.14.10/terraform_0.14.10_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: lee
      group: lee

- hosts: web_servers
  become: true
  tasks:

  - name: installation apache2, php packages and update index Ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache2, php packages and update index for CentOS
    dnf:
      name: 
         - httpd
         - php
      state: latest
    when: ansible_distribution in ["CentOS","RedHat"]
  
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: lee
      group: lee
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 


- hosts: file_servers
  become: yes
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
