
---
#Install targetting specific hosts
- hosts: all
  become: yes
  pre_tasks:

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
#      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2, php packages and update index Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache2, php packages and update index for CentOS
    tags: apache,httpd,centos
    dnf:
      name: 
         - httpd
         - php
      state: latest
    when: ansible_distribution in ["CentOS","RedHat"]


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,mariadb,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,ubuntu,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 


- hosts: file_servers
  become: yes
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
